# Generated by Django 5.1.1 on 2024-09-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('dob', models.CharField(max_length=100)),
                ('aadhar_no', models.IntegerField()),
                ('mobile_no', models.IntegerField()),
            ],
        ),
    ]
